import { createSlice } from '@reduxjs/toolkit'
import {
  User
} from 'firebase/auth'
import { RootState } from '@/libs'

/**
 * Represents the state structure for user-related data in Redux.
 */
export type UserState = {
  user: User | null;
};

/**
 * Initial state for the user slice.
 */
const initialState: UserState = {
  user: null
};

/**
 * Redux slice responsible for managing user-related actions and state.
 */
export const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    /**
     * Action creator for signing in a user.
     * @param state - The current user state.
     * @param action - The action object containing the user data payload.
     */
    signIn: (state, action) => {
      state.user = action.payload;
    },
    /**
     * Action creator for signing out a user.
     * @param state - The current user state.
     */
    signOut: (state) => {
      state.user = null;
    }
  }
});

/**
 * Action creators generated by the user slice.
 */
export const { signIn, signOut } = userSlice.actions;

/**
 * Selects the user data from the root state.
 * @param state - The root state of the application.
 * @returns The user data.
 */
export const selectUser = (state: RootState) => state.user;

/**
 * Reducer function for the user slice.
 */
export default userSlice.reducer;
